name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Toutes les 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render backend
        run: curl -s https://co2-hp4f.onrender.com/transport/list > /dev/null
